### ISSUE TITLE
No predicted tags with raw input

### ISSUE THREAD

**Issue by AngelAquino** [bplank/bilstm-aux#18]
Hello, and thank you for making this tagger available!

I tried running the tagger with the `--raw` and `--output` options, using an input file with one sentence per line and with space-separated tokens. But it seems that after prediction, once the `output_preds` function is called, the `pred_tags` for each sequence remains empty, and the output file stores only newline characters.

My current workaround is simply to reformat the input file to have one line per token and add my own dummy tags before parsing. But as far as I can see, the tagger successfully parses raw inputs anyway, and correctly stores the `words` and `tags` per sequence. This leads me to believe that the difference lies in the `predict` function behavior.

**Comment by robvanderg** [comment]
Dear AngelAquino, thanks for the issue!, It should be fixed with the last commit

**Comment by AngelAquino** [comment]
Thanks, it works fine now. :)
