### ISSUE TITLE
Token with Unicode Emoji

### ISSUE THREAD

**Issue by Horsmann** [bplank/bilstm-aux#5]
Hi,

I am applying a self-trained model to Twitter messages which might contain unicode emojis. The lstm tagger seems to have problems with those emojis. 

for instance:
```
lol	X
"	.
😂😂💯	X
```

I can help myself with substituting those cases with a text constant before I call the tagger but I wonder if this problem is known? 

I am using `python3` on a `linux` machine.

Best,

**Comment by bplank** [comment]
Hi Tobias! 

I fixed this 
(commit https://github.com/bplank/bilstm-aux/commit/27e6d277f1c4613b26ca37b2fbc1106deca6c69f)

I also added a --raw function that now accepts plain input (one sentence per line)

Greetings
